/*!

@file
@verbatim
$Id:

Copyright (c) 2008-2009 DivX, Inc. All rights reserved.

This software is the confidential and proprietary information of DivXNetworks,
Inc. and may be used only in accordance with the terms of your license from
DivXNetworks, Inc.

@endverbatim

*/

// DivXErrorString.h - auto-generated by DivXErrParse.exe
// ** DO NOT modify this by hand - it will get overwritten **

#ifndef DivXErrorStringH
#define DivXErrorStringH

#include "DivXString.h"

/*! 
 * Defines the structure for error value and text
 */
typedef struct _DivXErr_Text {
  int32_t errorCode; // Error code
  DivXString *errorText; // Generated from comments
} DivXErr_Text;


/*! 
 * These are sorted numerically in ascending order and are a subset of the error
 * code strings in DivXError
 */
DivXErr_Text errorDescriptions[] = {
  { -14382, DIVX_STR("Required input ID is invalid (e.g. MEDS id)") },
  { -14381, DIVX_STR("Container is in an invalid write state for this operation") },
  { -14380, DIVX_STR("Read operations not supported by this module") },
  { -14379, DIVX_STR("Read operation not allowed on this container") },
  { -14378, DIVX_STR("Write operations not supported by this module") },
  { -14377, DIVX_STR("Write operation not allowed on this container") },
  { -14376, DIVX_STR("Attempt to create stream failed") },
  { -14375, DIVX_STR("Stream type specified with AddStream not supported") },
  { -14374, DIVX_STR("Stream type specified with SetBlock not supported") },
  { -14373, DIVX_STR("Invalid data encountered in idx1 entry (AVI)") },
  { -14372, DIVX_STR("Missing or invalid data in audio format") },
  { -14371, DIVX_STR("Missing or invalid data in video format") },
  { -14370, DIVX_STR("Video data is missing required frame rate information") },
  { -14369, DIVX_STR("Invalid stream handle specified (should be origin:1)") },
  { -14368, DIVX_STR("Data (metadata) is optional and not present") },
  { -14367, DIVX_STR("Container write failed due to insufficient disk space") },
  { -14366, DIVX_STR("Failed to create container due to missing required data from callback") },
  { -14365, DIVX_STR("Failed to create container - unspecified error in layer 1") },
  { -14364, DIVX_STR("Unexpected FourCC in container") },
  { -14363, DIVX_STR("Other container file i/o operation failed") },
  { -14362, DIVX_STR("Container file write failed") },
  { -14361, DIVX_STR("Container file read failed") },
  { -14360, DIVX_STR("Container missing required microsec/frame value") },
  { -14359, DIVX_STR("Operation requires a timecode value") },
  { -14358, DIVX_STR("Supplied buffer size is insufficient") },
  { -14357, DIVX_STR("Invalid frame rate in container") },
  { -14356, DIVX_STR("Invalid stream index") },
  { -14355, DIVX_STR("Invalid index supplied with query") },
  { -14354, DIVX_STR("Container initial low-level parse failed") },
  { -14353, DIVX_STR("Container open failed") },
  { -14352, DIVX_STR("Invalid data type component of query ID") },
  { -14351, DIVX_STR("A required argument pointer was null") },
  { -14350, DIVX_STR("Invalid query ID specified") },
  { -14349, DIVX_STR("Memory allocation failure") },
  { -14348, DIVX_STR("General query failure") },
  { -14347, DIVX_STR("Unable to read specified title") },
  { -14346, DIVX_STR("Invalid title handle specified") },
  { -14345, DIVX_STR("Invalid title index specified") },
  { -14344, DIVX_STR("Menu not found") },
  { -14343, DIVX_STR("Unable to get title count") },
  { -14342, DIVX_STR("Embedded handle has invalid module ID") },
  { -14341, DIVX_STR("Required data for OpenContainer invalid") },
  { -14340, DIVX_STR("Filename not supplied") },
  { -14339, DIVX_STR("Container not opened") },
  { -14338, DIVX_STR("Invalid handle") },
  { -14337, DIVX_STR("Module not initialized") },
  { -13320, DIVX_STR("Data requested via callback from CreateContainer not specified") },
  { -13319, DIVX_STR("No L1 module found to support specified container") },
  { -13318, DIVX_STR("Null pointer supplied for required argument") },
  { -13317, DIVX_STR("Module ID out of range") },
  { -13316, DIVX_STR("Cannot perform operation with null module ID") },
  { -13315, DIVX_STR("Entry point undefined") },
  { -13314, DIVX_STR("Invalid handle") },
  { -13313, DIVX_STR("Module not initialized") },
  { -9, DIVX_STR("End of file reached while reading") },
  { -8, DIVX_STR("Invalid request") },
  { -7, DIVX_STR("Error code out of range") },
  { -6, DIVX_STR("Invalid state") },
  { -5, DIVX_STR("General write failure") },
  { -4, DIVX_STR("General read failure") },
  { -3, DIVX_STR("Open file or container failed") },
  { -2, DIVX_STR("Supplied argument invalid") },
  { -1, DIVX_STR("General undefined error") },
  { 1, DIVX_STR("General nonfatal warning") },
  { 2, DIVX_STR("Nonfatal warning for invalid handle") },
  { 14337, DIVX_STR("Reached EOF on ReadNextBlock()") },
  { 14338, DIVX_STR("SetBlock() attempted past end") }
};

// End of table
#define DIVX_ERR_STRING_COUNT (sizeof(errorDescriptions)/sizeof(errorDescriptions[0]))

#endif
// end of generated code

